// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKGiZcSM_PnN_ERhRed94LjIaK3nPkahM',
    appId: '1:974016512252:web:c356dafda3972f575d5779',
    messagingSenderId: '974016512252',
    projectId: 'spotifyclone0101',
    authDomain: 'spotifyclone0101.firebaseapp.com',
    storageBucket: 'spotifyclone0101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOapGP118ZHQFz9lL8W5gpdtEC3ANMiAU',
    appId: '1:974016512252:android:f0f46b75101a31ca5d5779',
    messagingSenderId: '974016512252',
    projectId: 'spotifyclone0101',
    storageBucket: 'spotifyclone0101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMCP3U1tq_-fmjf5BV1W91xdn2-oa2ECE',
    appId: '1:974016512252:ios:f84fe4dbad5fc2cb5d5779',
    messagingSenderId: '974016512252',
    projectId: 'spotifyclone0101',
    storageBucket: 'spotifyclone0101.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMCP3U1tq_-fmjf5BV1W91xdn2-oa2ECE',
    appId: '1:974016512252:ios:f84fe4dbad5fc2cb5d5779',
    messagingSenderId: '974016512252',
    projectId: 'spotifyclone0101',
    storageBucket: 'spotifyclone0101.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKGiZcSM_PnN_ERhRed94LjIaK3nPkahM',
    appId: '1:974016512252:web:217817c8c6d968f95d5779',
    messagingSenderId: '974016512252',
    projectId: 'spotifyclone0101',
    authDomain: 'spotifyclone0101.firebaseapp.com',
    storageBucket: 'spotifyclone0101.appspot.com',
  );
}
